FROM deersheep330/python-chrome-crontab

ENV TZ=Asia/Taipei

WORKDIR /home/app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY ./stock ./stock
COPY ./test.py .
COPY ./wait-for-it.sh .

RUN chmod +x /home/app/wait-for-it.sh

# Run the command on container startup
CMD ./wait-for-it.sh $DB_HOST && python test.py
