"""empty message

Revision ID: 95b85747d2e3
Revises: 
Create Date: 2021-07-22 23:50:30.808931

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '95b85747d2e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twse_close_price', sa.Column('change', sa.Float(), nullable=True))
    op.add_column('twse_close_price', sa.Column('percentage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twse_close_price', 'percentage')
    op.drop_column('twse_close_price', 'change')
    # ### end Alembic commands ###
